"""
Core domain models for the Enterprise AIOps platform.

These are the canonical data structures that flow through the entire system —
from alert ingestion, through the LangGraph agent pipeline, to API responses
and the Streamlit dashboard.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

from app.domain.enums import (
    AlertType,
    Environment,
    IncidentStatus,
    RemediationActionType,
    Severity,
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


# ── Core Models ───────────────────────────────────────────────────────────────

class Alert(BaseModel):
    """
    An incoming monitoring alert from any observability source
    (Prometheus, Datadog, CloudWatch, PagerDuty, etc.).
    """

    alert_id: str = Field(default_factory=_new_uuid)
    source: str = Field(..., description="Monitoring source system (e.g., Prometheus)")
    service: str = Field(..., description="Name of the affected service")
    alert_type: AlertType = Field(..., description="Alert classification")
    title: str = Field(..., description="Short, human-readable alert title")
    description: str = Field(..., description="Detailed alert description")
    metric_value: Optional[float] = Field(None, description="Observed metric value at alert time")
    threshold_value: Optional[float] = Field(None, description="Configured threshold that was breached")
    labels: dict[str, str] = Field(default_factory=dict, description="Metadata labels (env, region, team, etc.)")
    raw_payload: dict[str, Any] = Field(default_factory=dict, description="Full original alert payload")
    received_at: datetime = Field(default_factory=_utcnow)

    @field_validator("service")
    @classmethod
    def normalize_service_name(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("service name cannot be empty")
        return v.lower().strip().replace(" ", "-")

    @field_validator("source")
    @classmethod
    def normalize_source(cls, v: str) -> str:
        return v.strip()


class MetricSnapshot(BaseModel):
    """Point-in-time snapshot of a single metric, attached to an RCA finding."""

    metric_name: str
    value: float
    unit: str
    timestamp: datetime = Field(default_factory=_utcnow)
    tags: dict[str, str] = Field(default_factory=dict)


class RCAFinding(BaseModel):
    """
    A single root cause analysis finding produced by the RCA agent node.
    Multiple findings are ranked by confidence and presented together.
    """

    component: str = Field(..., description="System component implicated (service, DB, queue, etc.)")
    finding: str = Field(..., description="Human-readable description of the finding")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0 and 1")
    supporting_metrics: list[MetricSnapshot] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list, description="Log lines, events, or trace IDs")


class RemediationStep(BaseModel):
    """
    A single actionable remediation step generated by the remediation agent node.
    Steps are ordered by priority and can be auto-executed or require approval.
    """

    action: RemediationActionType
    description: str
    command: Optional[str] = Field(None, description="Exact runbook command or kubectl/CLI snippet")
    estimated_duration_seconds: int = Field(60, ge=1)
    requires_approval: bool = Field(True, description="False only when AUTO_REMEDIATION=true and risk is low")
    priority: int = Field(1, ge=1, le=5, description="Execution order — 1 is highest priority")


class Incident(BaseModel):
    """
    The canonical incident record. Created from an Alert and progressively
    enriched as it moves through the LangGraph agent pipeline.
    """

    incident_id: str = Field(default_factory=lambda: f"INC-{_new_uuid()[:8].upper()}")
    alert: Alert
    severity: Severity = Field(Severity.UNKNOWN)
    status: IncidentStatus = Field(IncidentStatus.OPEN)
    environment: Environment = Field(Environment.PRODUCTION)
    affected_service: str = Field("")
    summary: str = Field("")
    rca_findings: list[RCAFinding] = Field(default_factory=list)
    remediation_steps: list[RemediationStep] = Field(default_factory=list)
    agent_notes: list[str] = Field(default_factory=list)
    execution_path: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=_utcnow)
    resolved_at: Optional[datetime] = None
    resolution_summary: Optional[str] = None

    @property
    def duration_seconds(self) -> Optional[float]:
        """Wall-clock seconds from creation to resolution."""
        if self.resolved_at:
            return (self.resolved_at - self.created_at).total_seconds()
        return None

    @property
    def top_rca_finding(self) -> Optional[RCAFinding]:
        """Highest-confidence RCA finding, if any."""
        if not self.rca_findings:
            return None
        return max(self.rca_findings, key=lambda f: f.confidence)


class AgentRunResult(BaseModel):
    """
    The final output returned by the incident service after a complete
    agent pipeline run. This is what the API and dashboard consume.
    """

    incident: Incident
    total_duration_ms: float = Field(0.0, description="End-to-end pipeline latency in milliseconds")
    success: bool = True
    error_message: Optional[str] = None
